### ISSUE TITLE
Link to Documentation from README is broken

### ISSUE THREAD

**Issue by RaoOfPhysics** [inveniosoftware/invenio-pages#36]
http://pythonhosted.org/invenio-orcid/ gives a 404 page.

Can fix if provided with the right link or can remove if no documentation exists. Please let me know.

**Comment by hachreak** [comment]
Hi @RaoOfPhysics 
Yes, we should ask to @lnielsen or @jirikuncar or @tiborsimko .
P.s. I think you created the issue in the wrong module... XD

**Comment by RaoOfPhysics** [comment]
@hachreak: Ugh, you're right. Will close and open the issue in the correct module's repo.
