### ISSUE TITLE
Move pages CLI to invenio-pages

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-pages#56]
Currently there is a CLI that creates and re-creates the static pages, this CLI is defined in invenio-rdm-records (see this [comment](https://github.com/inveniosoftware/invenio-rdm-records/pull/1142#discussion_r1053020792)). Move the CLI to invenio-pages and add tests.

**Comment by kpsherva** [comment]
closing, the pages are created as fixtures in invenio-app-rdm
