### ISSUE TITLE
URLs are not registered correctly

### ISSUE THREAD

**Issue by jrcastro2** [inveniosoftware/invenio-pages#58]
The url registering is not working, URLs are not being registered in the app ([here the code](https://github.com/inveniosoftware/invenio-pages/blob/master/invenio_pages/views.py#L106) that was supposed to do it, but is not registering it properly) and it's falling back all the time in the `handle_not_found` function all the time. 
Make sure URLs are being registered, maybe invenio-administration could have some examples on how to do it.
Add tests for this.

**Comment by ntarocco** [comment]
They are registered after the first `404`, right?

**Comment by jrcastro2** [comment]
> They are registered after the first `404`, right?

Unfortunately not, that's the problem.
After the first 404 or in version 1.x.x before the first request it's supossed to register it (see code [here](https://github.com/inveniosoftware/invenio-pages/blob/master/invenio_pages/views.py#L106)), but it's not working. Ff I try to register them manually I get the following error:
```
AssertionError: The setup method 'add_url_rule' can no longer be called on the application. It has already handled its first request, any changes will not be applied consistently.
Make sure all imports, decorators, functions, etc. needed to set up the application are done before running it.
```
I guess it fails silently, not allowing to register them at that point ... This means that every request it will be catched by the 404 and "try" to register the URL and render the template using the code in the 404, not the view function for that endpoint.
